//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DokumentMagazynowy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DokumentMagazynowy()
        {
            this.PozycjaDokumentuMagazynowego = new HashSet<PozycjaDokumentuMagazynowego>();
        }
    
        public int IdDokumentuMagazynowego { get; set; }
        public string Numer { get; set; }
        public System.DateTime DataDokumentu { get; set; }
        public int IdMagazynu { get; set; }
        public int IdTypuDokumentu { get; set; }
        public string Uwagi { get; set; }
    
        public virtual Magazyn Magazyn { get; set; }
        public virtual TypDokumentuMagazynowego TypDokumentuMagazynowego { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PozycjaDokumentuMagazynowego> PozycjaDokumentuMagazynowego { get; set; }
    }
}
