//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FakturaSprzedazy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FakturaSprzedazy()
        {
            this.PozycjaFakturySprzedazy = new HashSet<PozycjaFakturySprzedazy>();
        }
    
        public int IdFakturySprzedazy { get; set; }
        public string Numer { get; set; }
        public System.DateTime DataWystawienia { get; set; }
        public System.DateTime DataSprzedazy { get; set; }
        public int IdKontrahenta { get; set; }
        public Nullable<int> IdSposobuPlatnosci { get; set; }
        public Nullable<int> IdStatusuFaktury { get; set; }
        public Nullable<int> IdWaluty { get; set; }
        public Nullable<System.DateTime> TerminPlatnosci { get; set; }
        public Nullable<decimal> RazemNetto { get; set; }
        public Nullable<decimal> RazemVat { get; set; }
        public Nullable<decimal> RazemBrutto { get; set; }
    
        public virtual Kontrahent Kontrahent { get; set; }
        public virtual SposobPlatnosci SposobPlatnosci { get; set; }
        public virtual StatusFaktury StatusFaktury { get; set; }
        public virtual Waluta Waluta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PozycjaFakturySprzedazy> PozycjaFakturySprzedazy { get; set; }
    }
}
