//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontrahent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kontrahent()
        {
            this.AdresKontrahenta = new HashSet<AdresKontrahenta>();
            this.FakturaSprzedazy = new HashSet<FakturaSprzedazy>();
            this.ZamowienieSprzedazy = new HashSet<ZamowienieSprzedazy>();
        }
    
        public int IdKontrahenta { get; set; }
        public string NIP { get; set; }
        public bool CzyAktywny { get; set; }
        public Nullable<int> IdTypuKontrahenta { get; set; }
        public string NazwaPelna { get; set; }
        public string NazwaSkrocona { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdresKontrahenta> AdresKontrahenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FakturaSprzedazy> FakturaSprzedazy { get; set; }
        public virtual TypKontrahenta TypKontrahenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZamowienieSprzedazy> ZamowienieSprzedazy { get; set; }
    }
}
