//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FakturyEntities : DbContext
    {
        public FakturyEntities()
            : base("name=FakturyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kontrahent> Kontrahent { get; set; }
        public virtual DbSet<SposobPlatnosci> SposobPlatnosci { get; set; }
        public virtual DbSet<Towar> Towar { get; set; }
        public virtual DbSet<AdresKontrahenta> AdresKontrahenta { get; set; }
        public virtual DbSet<DokumentMagazynowy> DokumentMagazynowy { get; set; }
        public virtual DbSet<FakturaSprzedazy> FakturaSprzedazy { get; set; }
        public virtual DbSet<JednostkaMiary> JednostkaMiary { get; set; }
        public virtual DbSet<KategoriaTowaru> KategoriaTowaru { get; set; }
        public virtual DbSet<Magazyn> Magazyn { get; set; }
        public virtual DbSet<PozycjaDokumentuMagazynowego> PozycjaDokumentuMagazynowego { get; set; }
        public virtual DbSet<PozycjaFakturySprzedazy> PozycjaFakturySprzedazy { get; set; }
        public virtual DbSet<PozycjaZamowieniaSprzedazy> PozycjaZamowieniaSprzedazy { get; set; }
        public virtual DbSet<StanMagazynowy> StanMagazynowy { get; set; }
        public virtual DbSet<StatusFaktury> StatusFaktury { get; set; }
        public virtual DbSet<StatusZamowienia> StatusZamowienia { get; set; }
        public virtual DbSet<StawkaVat> StawkaVat { get; set; }
        public virtual DbSet<TypDokumentuMagazynowego> TypDokumentuMagazynowego { get; set; }
        public virtual DbSet<TypKontrahenta> TypKontrahenta { get; set; }
        public virtual DbSet<Waluta> Waluta { get; set; }
        public virtual DbSet<ZamowienieSprzedazy> ZamowienieSprzedazy { get; set; }
    }
}
