//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PozycjaDokumentuMagazynowego
    {
        public int IdPozycjiDokumentuMagazynowego { get; set; }
        public int IdDokumentuMagazynowego { get; set; }
        public int IdTowaru { get; set; }
        public decimal Ilosc { get; set; }
    
        public virtual DokumentMagazynowy DokumentMagazynowy { get; set; }
        public virtual Towar Towar { get; set; }
    }
}
