//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PozycjaZamowieniaSprzedazy
    {
        public int IdPozycjiZamowieniaSprzedazy { get; set; }
        public int IdZamowieniaSprzedazy { get; set; }
        public int IdTowaru { get; set; }
        public decimal Ilosc { get; set; }
        public decimal CenaNetto { get; set; }
    
        public virtual Towar Towar { get; set; }
        public virtual ZamowienieSprzedazy ZamowienieSprzedazy { get; set; }
    }
}
