//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PozycjaFakturySprzedazy
    {
        public int IdPozycjiFakturySprzedazy { get; set; }
        public int IdFakturySprzedazy { get; set; }
        public int IdTowaru { get; set; }
        public decimal Ilosc { get; set; }
        public decimal CenaNetto { get; set; }
        public Nullable<int> IdStawkiVat { get; set; }
        public Nullable<decimal> WartoscNetto { get; set; }
        public Nullable<decimal> WartoscVat { get; set; }
        public Nullable<decimal> WartoscBrutto { get; set; }
    
        public virtual FakturaSprzedazy FakturaSprzedazy { get; set; }
        public virtual StawkaVat StawkaVat { get; set; }
        public virtual Towar Towar { get; set; }
    }
}
