//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Towar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Towar()
        {
            this.PozycjaDokumentuMagazynowego = new HashSet<PozycjaDokumentuMagazynowego>();
            this.PozycjaFakturySprzedazy = new HashSet<PozycjaFakturySprzedazy>();
            this.PozycjaZamowieniaSprzedazy = new HashSet<PozycjaZamowieniaSprzedazy>();
            this.StanMagazynowy = new HashSet<StanMagazynowy>();
        }
    
        public int IdTowaru { get; set; }
        public string Kod { get; set; }
        public string Nazwa { get; set; }
        public decimal Cena { get; set; }
        public Nullable<decimal> Marza { get; set; }
        public bool CzyAktywny { get; set; }
        public Nullable<int> IdKategoriiTowaru { get; set; }
        public Nullable<int> IdJednostkiMiary { get; set; }
        public Nullable<int> IdStawkiVatSprzedazy { get; set; }
        public Nullable<int> IdStawkiVatZakupu { get; set; }
    
        public virtual JednostkaMiary JednostkaMiary { get; set; }
        public virtual KategoriaTowaru KategoriaTowaru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PozycjaDokumentuMagazynowego> PozycjaDokumentuMagazynowego { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PozycjaFakturySprzedazy> PozycjaFakturySprzedazy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PozycjaZamowieniaSprzedazy> PozycjaZamowieniaSprzedazy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StanMagazynowy> StanMagazynowy { get; set; }
        public virtual StawkaVat StawkaVat { get; set; }
        public virtual StawkaVat StawkaVat1 { get; set; }
    }
}
