//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZamowienieSprzedazy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZamowienieSprzedazy()
        {
            this.PozycjaZamowieniaSprzedazy = new HashSet<PozycjaZamowieniaSprzedazy>();
        }
    
        public int IdZamowieniaSprzedazy { get; set; }
        public string Numer { get; set; }
        public System.DateTime DataZamowienia { get; set; }
        public int IdKontrahenta { get; set; }
        public Nullable<int> IdStatusuZamowienia { get; set; }
        public string Uwagi { get; set; }
    
        public virtual Kontrahent Kontrahent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PozycjaZamowieniaSprzedazy> PozycjaZamowieniaSprzedazy { get; set; }
        public virtual StatusZamowienia StatusZamowienia { get; set; }
    }
}
